### PR TITLE
Make the commerce requirement to be 2.14

### PR DESCRIPTION
**Pull request by safalliajoseph**
This MR jus downgrades the commerce module requirements to 2.14

### CODE REVIEW

**Comment by safalliajoseph** [comment]
@shabananavas Could you please review

**Comment by shabananavas** [comment]
Looks good. Please push to d.org.

**Comment by safalliajoseph** [comment]
@shabananavas I am not sure if I have the access to merge to d.o. I do not have the maintainer access I think.

**Comment by shabananavas** [comment]
@thenchev Saf will create a couple of MRs on d.org for these new issues and mark them as Needs Review. I'll review and RTBC them. Could you then please merge these in.

**Pull request merged**
