### PR TITLE
Code fix

### PR DESCRIPTION
**Pull request by safalliajoseph**
The update functions name fix

### CODE REVIEW

**Comment by safalliajoseph** [comment]
@shabananavas @thenchev There was a method naming error in the code. @thenchev Could you please merge this in directly. Do I have to create a patch for this?

**Comment by shabananavas** [comment]
> @shabananavas @thenchev There was a method naming error in the code. @thenchev Could you please merge this in directly. Do I have to create a patch for this?

I know it's a pain, but I think the proper way to go is to create a bug issue on d.org and create a patch for it there.

**Comment by safalliajoseph** [comment]
https://www.drupal.org/project/3111714/issues/3131773#comment-13576648 - Here you go. 
@thenchev Could you merge this in

**Comment by shabananavas** [comment]
Thanks for the fixing that quickly Saf and merging that in Milos. But I just noticed something about the merging. I think we are doing it wrong. We are correctly committing to d.org.

However, we don't merge the MRs in github. We want to keep the same exact git history as d.org here. So,  we push the d.org 8.x-1.x to the 8.x-1.x branch here. We, then, just close the open PR here.

Notice the commits for Commerce Hubspot on github: https://github.com/krystalcode/drupal8-commerce-hubspot/commits/8.x-1.x. They're a mirror of d.org. However, if you look at the commits for 8.x-1.x in this repo, they're all from merging the PRs in.

So, this would be the workflow:

- Clone the d.org repo (remote name: origin)
- Add the github repo as a remote (remote name: github)
- Create a branch off of the github 8.x-1.x and create PRs off of it
- Once the work is RTBC'd on d.org, we commit it to d.org's 8.x-1.x branch
```
git add .
git commit -m 'Issue #3131552 by shabana.navas, thenchev: Remove incorrect mapping' --author="ShabanaBlackborder <ShabanaBlackborder@1311398.no-reply.drupal.org>"
git push origin
```
- We then push that same d.org 8.x-1.x branch to github's 8.x-1.x branch
```
git push github 8.x-1.x
``` 

Let's leave things as is for now, we can work on getting the 8.x-1.x here same as d.org's, once everything is done for Commerce Options.

**Comment by thenchev** [comment]
@shabananavas that would make things a lot easier, i thought we were not adding remotes. I'm all for it, lets look into that later then

**Comment by shabananavas** [comment]
I'm sorry, yeah, I think that was a miscommunication from my end. I actually meant this.

**Pull request merged**
